### PR TITLE
added html boilerplate

### PR DESCRIPTION
**Pull request by zoeames**

### CODE REVIEW

**Comment by rousell** [comment]
@zoeames This looks great!

**Comment by rousell** [comment]
👍

**Comment by zoeames** [comment]
👍

**Comment by morecallan** [comment]
🥇

**Comment by morecallan** [comment]
I mean... it could use more pink.

**Comment by morecallan** [comment]
giphy

**Comment by zoeames** [comment]
@morecallan  is that better?

**Pull request merged**
